language: python
python:
  - "3.9"

services:
  - docker

env:
  global:
    - SECRET_KEY=secret
    - DB_NAME=farafmb
    - DB_USER=farafmb
    - DB_PASSWORD=secret
    - EMAIL_HOST=localhost
    - EMAIL_PORT=25
    - EMAIL_USER=farafmb
    - EMAIL_PASSWORD=secret
    - DEFAULT_EMAIL="noreply@example.com"
    - SERVER_EMAIL="noreply@example.com"

before_install:
  - docker-compose --version
  - docker-compose config
  - docker-compose up -d --build
  - docker run farafmb /bin/sh -c "python manage.py test --noinput"

script:
  - python manage.py test --noinput
