language: python
python:
  - "3.9"

services:
  - docker

before_install:
  - docker build -t timptner/farafmb .
  - docker run -d timptner/farafmb
  - docker ps -a
  - docker run timptner/farafmb /bin/sh -c "python manage.py test --noinput"

script:
  - python manage.py test --noinput
