language: python
python:
  - "3.9"

services:
  - docker

before_install:
  - docker-compose --version
  - docker-compose config
  - docker-compose up -d
  - docker run farafmb /bin/sh -c "python manage.py test --noinput"

script:
  - python manage.py test --noinput
