version: "3.9"
services:
  farafmb:
    build: .
    image: timptner/farafmb
    container_name: farafmb
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DB_HOST=farafmb_db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - OIDC_CLIENT_ID=${OIDC_CLIENT_ID}
      - OIDC_CLIENT_SECRET=${OIDC_CLIENT_SECRET}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - DEFAULT_EMAIL=${DEFAULT_EMAIL}
      - SERVER_EMAIL=${SERVER_EMAIL}
    volumes:
      - ${MEDIA_DIR:-./media}:/home/farafmb/media
      - ${STATIC_DIR:-./static}:/home/farafmb/static
    ports:
      - "${DOCKER_PORT:-127.0.0.1:5000}:5000"
    depends_on:
      - farafmb_db
    restart: unless-stopped
  farafmb_db:
    image: postgres:14-alpine
    container_name: farafmb_db
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ${DATABASE_DIR:-./database}:/var/lib/postgresql/data
    restart: unless-stopped
