[project]
name = "farafmb"
version = "2024.1"
dependencies = [
    "bleach",
    "Django~=5.1.2",
    "Markdown",
    "markdown-checklist",
    "markdown-del-ins",
    "Pillow",
    "psycopg",
    "python-dotenv",
]

[project.optional-dependencies]
"development" = ["djlint", "coverage"]
