name: test & build

on:
  push:
    branches:
      - main

# env:
#   REGISTRY: ghcr.io
#   IMAGE_NAME: ${{ github.repository }}

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: farafmb
          POSTGRES_USER: farafmb
          POSTGRES_PASSWORD: secret
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: install dependencies
        run: python3 -m pip install -r requirements.txt
      - name: run tests
        run: python manage.py test --no-input --failfast
        env:
          DATABASE_HOST: localhost
          DATABASE_PORT: 5432
          DATABASE_PASSWORD: secret

  # build:
  #   needs: test

  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: read buildah version
  #       run: buildah --version
  #     - name: build container
  #       run: ./build.sh
  #     -
  #     - uses: actions/upload-artifact@v4
  #       with:
  #         name: farafmb
  #         path:
