name: Deploy django app to remote host

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    permissions:
      contents: none
    
    runs-on: ubuntu-latest
    environment:
      name: 'production'

    steps:
      - name: Create private ssh key
        run: |
          mkdir -p ~/.ssh
          chmod 0700 ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 0600 ~/.ssh/id_rsa
          ls -lha ~/.ssh/
          ssh -o StrictHostKeyChecking=accept-new "${{ vars.SSH_USER }}@${{ vars.SSH_HOST }}"
          cd "${{ vars.REPO_PATH }}"
          git status
