name: Docker

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: farafmb

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up docker-compose
        env:
          SECRET_KEY: secret
          DB_NAME: farafmb
          DB_USER: farafmb
          DB_PASSWORD: secret
          OIDC_CLIENT_ID: client
          OIDC_CLIENT_SECRET: secret
          EMAIL_HOST: localhost
          EMAIL_PORT: 25
          EMAIL_USER: farafmb
          EMAIL_PASSWORD: secret
          DEFAULT_EMAIL: noreply@example.org
          SERVER_EMAIL: noreply@example.org
        run: |
          cp docker-compose.override.yaml.example docker-compose.override.yaml
          docker-compose up --build -d
          sleep 10
          docker ps
          docker-compose logs
      - name: Run tests
        run: |
          docker exec ${{ env.IMAGE_NAME }} python manage.py migrate --no-input
          # docker exec ${{ env.IMAGE_NAME }} python manage.py collectstatic --no-input
          docker exec ${{ env.IMAGE_NAME }} python manage.py test --no-input
      - name: Log in to GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push image
        run: |
          IMAGE_ID=${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
          # Make image id lower case
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          # Label with version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION) | sed -e 's/^v//')
          [ "$VERSION" == "master" ] && VERSION=latest
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
