name: Docker

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup docker-compose
        env:
          SECRET_KEY: secret
          DB_NAME: farafmb
          DB_USER: farafmb
          DB_PASSWORD: secret
          OIDC_CLIENT_ID: client
          OIDC_CLIENT_SECRET: secret
          EMAIL_HOST: localhost
          EMAIL_PORT: 25
          EMAIL_USER: farafmb
          EMAIL_PASSWORD: secret
          DEFAULT_EMAIL: noreply@example.org
          SERVER_EMAIL: noreply@example.org
        run: |
          docker-compose --version
          docker-compose up -d
          docker images
          docker ps
      - name: Run tests
        run: |
          docker exec farafmb python manage.py test --noinput
